services:
  selenium-hub:
    image: selenium/hub:4.24.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - pipeline_automation_grid
    environment:
      - GRID_MAX_SESSION=1
      - GRID_BROWSER_TIMEOUT=300

  chrome:
    image: selenium/node-chrome:4.24.0
    container_name: selenium-chrome
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_NODE_BROWSER_ARGS=--no-sandbox --disable-dev-shm-usage --disable-gpu
    networks:
      - pipeline_automation_grid
    ports:
      - "7900:7900"
  tests:
    build: .
    container_name: selenium-tests
    depends_on:
      - selenium-hub
      - chrome
    networks:
      - pipeline_automation_grid
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./reports:/app/reports
      - ./target:/app/target 
    environment:
      - MAVEN_OPTS=-Xmx512m
    command: >
      /bin/bash -c "
      echo 'Waiting for Selenium Grid to be ready...';
      sleep 30;
      mvn clean test -Dextent.output.dir=/app/reports
      "

networks:
  pipeline_automation_grid:
    driver: bridge
